### ISSUE TITLE
Erweiterung kann derzeit nicht installiert werden !!!

### ISSUE THREAD

**Issue by Cleanerrr** [Kuestenschmiede/ReservationBundle#12]
`> Resolving dependencies using Composer Cloud v3.2.0
!!! Current server is sponsored by: Contao Association !!!
[7.3MiB/0.19s] Loading composer repositories with package information
[62.3MiB/1.67s] Updating dependencies
[1453.0MiB/16.24s] Your requirements could not be resolved to an installable set of packages.
[1453.0MiB/16.24s] 
  Problem 1
    - Root composer.json requires contao/calendar-bundle 4.11.* -> satisfiable by contao/calendar-bundle[4.11.0, ..., 4.11.5].
    - Conclusion: don't install symfony/http-kernel v5.2.2 (conflict analysis result)
    - Conclusion: don't install symfony/http-kernel v5.2.3 (conflict analysis result)
    - Conclusion: don't install symfony/http-kernel v5.2.4 (conflict analysis result)
    - Conclusion: don't install symfony/http-kernel v5.2.5 (conflict analysis result)
    - Conclusion: don't install symfony/framework-bundle v5.2.3 (conflict analysis result)
    - Conclusion: don't install symfony/console v4.4.26 (conflict analysis result)
    - Conclusion: don't install symfony/http-kernel v5.2.6 (conflict analysis result)
    - Conclusion: don't install symfony/http-kernel v5.2.7 (conflict analysis result)
    - Conclusion: don't install symfony/http-kernel v5.2.8 (conflict analysis result)
    - Conclusion: don't install symfony/http-kernel v5.2.9 (conflict analysis result)
    - Conclusion: don't install symfony/http-kernel v5.2.10 (conflict analysis result)
    - Conclusion: don't install symfony/http-kernel v5.2.11 (conflict analysis result)
    - Conclusion: don't install symfony/framework-bundle v5.2.4 (conflict analysis result)
    - Conclusion: don't install symfony/console v5.2.0 (conflict analysis result)
    - Conclusion: don't install symfony/console v5.2.1 (conflict analysis result)
    - Conclusion: don't install symfony/framework-bundle v5.2.5 (conflict analysis result)
    - Conclusion: don't install symfony/console v5.2.2 (conflict analysis result)
    - Conclusion: don't install symfony/framework-bundle v5.2.6 (conflict analysis result)
    - Conclusion: don't install symfony/console v5.2.3 (conflict analysis result)
    - Conclusion: don't install symfony/framework-bundle v5.2.7 (conflict analysis result)
    - Conclusion: don't install symfony/console v5.2.4 (conflict analysis result)
    - Conclusion: don't install symfony/framework-bundle v5.2.9 (conflict analysis result)
    - Conclusion: don't install symfony/framework-bundle v5.2.10 (conflict analysis result)
    - Conclusion: don't install symfony/framework-bundle v5.2.11 (conflict analysis result)
    - Conclusion: don't install symfony/console v5.2.5 (conflict analysis result)
    - Conclusion: don't install symfony/console v5.2.6 (conflict analysis result)
    - Conclusion: don't install symfony/console v5.2.7 (conflict analysis result)
    - Conclusion: don't install symfony/console v5.2.8 (conflict analysis result)
    - Conclusion: don't install symfony/http-kernel v5.3.0 (conflict analysis result)
    - Conclusion: don't install symfony/http-kernel v5.3.1 (conflict analysis result)
    - Conclusion: don't install symfony/http-kernel v5.3.2 (conflict analysis result)
    - Conclusion: don't install symfony/http-kernel v5.3.3 (conflict analysis result)
    - Conclusion: don't install one of menatwork/contao-multicolumnwizard-bundle[3.4.11], symfony/console[v5.2.11] (conflict analysis result)
    - Conclusion: don't install one of menatwork/contao-multicolumnwizard-bundle[3.4.11], symfony/console[v5.2.10] (conflict analysis result)
    - Conclusion: install menatwork/contao-multicolumnwizard-bundle 3.4.11 (conflict analysis result)
    - contao/manager-bundle 4.11.2 requires contao/installation-bundle 4.11.2 -> satisfiable by contao/installation-bundle[4.11.2].
    - contao/manager-bundle 4.11.2 requires symfony/web-profiler-bundle 4.4.* || 5.2.* -> satisfiable by symfony/web-profiler-bundle[v5.2.7].
    - Root composer.json requires contao/conflicts *@dev -> satisfiable by contao/conflicts[dev-main].
    - contao/installation-bundle 4.11.2 requires symfony/framework-bundle 4.4.* || 5.2.* -> satisfiable by symfony/framework-bundle[v4.4.0, ..., v4.4.26, v5.2.0, ..., v5.2.11].
    - symfony/framework-bundle[v4.4.0, ..., v4.4.26] require symfony/http-kernel ^4.4 -> satisfiable by symfony/http-kernel[v4.4.0, ..., v4.4.26].
    - You can only install one version of a package, so only one of these can be installed: symfony/http-kernel[v2.1.0, ..., v2.8.52, v3.0.0, ..., v3.4.49, v4.0.0, ..., v4.4.26, v5.0.0, ..., v5.3.3].
    - symfony/web-profiler-bundle v5.2.7 requires symfony/http-kernel ^5.2 -> satisfiable by symfony/http-kernel[v5.2.0, ..., v5.3.3].
    - symfony/framework-bundle[v5.2.1, ..., v5.2.2] require symfony/http-kernel ^5.2.1 -> satisfiable by symfony/http-kernel[v5.2.1, ..., v5.3.3].
    - Conclusion: don't install symfony/http-kernel v5.2.1 (conflict analysis result)
    - contao/manager-bundle is locked to version 4.11.2 and an update of this package was not requested.
    - Root composer.json requires con4gis/reservation ^2.4 -> satisfiable by con4gis/reservation[v2.4.0, ..., v2.4.15].
    - contao/installation-bundle 4.11.2 requires symfony/console 4.4.* || 5.2.* -> satisfiable by symfony/console[v4.4.0, ..., v4.4.26, v5.2.0, ..., v5.2.11].
    - symfony/framework-bundle v5.2.0 conflicts with symfony/framework-bundle v5.2.0.
    - Conclusion: don't install symfony/console[v4.4.25] | install one of symfony/framework-bundle[v4.4.0, ..., v4.4.26, v5.2.4] (conflict analysis result)
[1453.0MiB/16.24s] <warning>Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.</warning>
[78.1MiB/17.63s] Memory usage: 78.08MB (peak: 1454.1MB), time: 17.63s.
[78.1MiB/17.63s] Finished Composer Cloud resolving.
# Cloud Job ID ZMCmDmJssBzlAbMXjjHaIRxnuVdc4vEywgaBqDHZDLBIO9MfCBhk8paVWs4oJjLUEdj7dx9F1NvHYr1XtgTw4R2JOOYmg7bQa7oUUYntS3FyMLqmhQq9 failed
composer install`

**Comment by coastforge-mei** [comment]
One problem is that the multicolumn wizard that the bundle uses (via con4gis/projects) is not yet available for Contao 4.11. Maybe this thread will help? https://community.contao.org/de/showthread.php?78261-Termine-buchen-M%C3%B6glichkeiten

We stay tuned.

**Comment by coastforge-mei** [comment]
Apparently it is this problem: https://github.com/menatwork/contao-multicolumnwizard-bundle/issues/107

We are now including the hotfix in the next version (today).

**Comment by Cleanerrr** [comment]
Thank you for your very fast response.

**Comment by Cleanerrr** [comment]
Hi again,
Unfortunately, I still have the same problem:
`> Resolving dependencies using Composer Cloud v3.2.0
!!! Current server is sponsored by: Contao Association !!!
[7.0MiB/0.18s] Loading composer repositories with package information
[61.3MiB/2.37s] Updating dependencies
[1446.3MiB/16.63s] Your requirements could not be resolved to an installable set of packages.
[1446.3MiB/16.64s] 
  Problem 1
    - Root composer.json requires contao/calendar-bundle 4.11.* -> satisfiable by contao/calendar-bundle[4.11.0, ..., 4.11.5].
    - Conclusion: don't install symfony/http-kernel v5.3.1 (conflict analysis result)
    - Conclusion: don't install symfony/http-kernel v5.3.2 (conflict analysis result)
    - Conclusion: don't install symfony/http-kernel v5.3.3 (conflict analysis result)
    - contao/manager-bundle 4.11.5 requires symfony/web-profiler-bundle 4.4.* || 5.2.* -> satisfiable by symfony/web-profiler-bundle[v5.2.11].
    - Root composer.json requires contao/conflicts *@dev -> satisfiable by contao/conflicts[dev-main].
    - Conclusion: don't install symfony/framework-bundle v4.4.25 (conflict analysis result)
    - Conclusion: don't install symfony/http-kernel v5.2.2 (conflict analysis result)
    - Conclusion: don't install symfony/http-kernel v5.2.3 (conflict analysis result)
    - Conclusion: don't install symfony/http-kernel v5.2.4 (conflict analysis result)
    - Conclusion: don't install symfony/http-kernel v5.2.5 (conflict analysis result)
    - Conclusion: don't install symfony/http-kernel v5.2.6 (conflict analysis result)
    - Conclusion: don't install symfony/framework-bundle v4.4.26 (conflict analysis result)
    - Conclusion: don't install symfony/http-kernel v5.2.7 (conflict analysis result)
    - Conclusion: don't install symfony/http-kernel v5.2.8 (conflict analysis result)
    - Conclusion: don't install symfony/http-kernel v5.2.9 (conflict analysis result)
    - Conclusion: don't install symfony/http-kernel v5.2.10 (conflict analysis result)
    - Conclusion: don't install symfony/http-kernel v5.2.11 (conflict analysis result)
    - Conclusion: don't install symfony/framework-bundle v5.2.0 (conflict analysis result)
    - Conclusion: don't install symfony/framework-bundle v5.2.1 (conflict analysis result)
    - Conclusion: don't install symfony/framework-bundle v5.2.2 (conflict analysis result)
    - Conclusion: don't install symfony/framework-bundle v5.2.3 (conflict analysis result)
    - Conclusion: don't install symfony/framework-bundle v5.2.4 (conflict analysis result)
    - Conclusion: don't install symfony/framework-bundle v5.2.5 (conflict analysis result)
    - Conclusion: don't install symfony/framework-bundle v5.2.6 (conflict analysis result)
    - Conclusion: don't install symfony/framework-bundle v5.2.7 (conflict analysis result)
    - Conclusion: don't install symfony/framework-bundle v5.2.9 (conflict analysis result)
    - Conclusion: don't install symfony/framework-bundle v5.2.10 (conflict analysis result)
    - Conclusion: don't install symfony/framework-bundle v5.2.11 (conflict analysis result)
    - Conclusion: don't install symfony/http-kernel v5.3.0 (conflict analysis result)
    - contao/manager-bundle is locked to version 4.11.5 and an update of this package was not requested.
    - Root composer.json requires con4gis/reservation ^2.4 -> satisfiable by con4gis/reservation[v2.4.0, ..., v2.4.16].
    - contao/manager-bundle 4.11.5 requires symfony/framework-bundle 4.4.* || 5.2.* -> satisfiable by symfony/framework-bundle[v4.4.0, ..., v4.4.26, v5.2.0, ..., v5.2.11].
    - symfony/framework-bundle[v4.4.0, ..., v4.4.24] require symfony/http-kernel ^4.4 -> satisfiable by symfony/http-kernel[v4.4.0, ..., v4.4.26].
    - You can only install one version of a package, so only one of these can be installed: symfony/http-kernel[v2.1.0, ..., v2.8.52, v3.0.0, ..., v3.4.49, v4.0.0, ..., v4.4.26, v5.0.0, ..., v5.3.3].
    - symfony/web-profiler-bundle v5.2.11 requires symfony/http-kernel ^5.2 -> satisfiable by symfony/http-kernel[v5.2.0, ..., v5.3.3].
    - Conclusion: don't install symfony/http-kernel v5.2.1 (conflict analysis result)
[1446.3MiB/16.64s] <warning>Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.</warning>
[77.6MiB/17.96s] Memory usage: 77.58MB (peak: 1447.73MB), time: 17.98s.
[77.6MiB/17.97s] Finished Composer Cloud resolving.
# Cloud Job ID D0WF7YAP27h6eNr21nEA94chYGD2BTFZVDyxVl4rjbkMYQmFPDpX7bD8A4ZRsupkatAslIPWgkNsqI1pGyZFBRA71MiiTCFPfHt0CpJAbFha1gamcJdtrHsDjBrSsL failed`

**Comment by coastforge-mei** [comment]
I made the correction in con4gis/projects. Maybe the bundle was not updated?

**Comment by Cleanerrr** [comment]
I don't know. I tried to install the plugin with Contao Manager, like usual. (con4gis-Reservation)
This morning also same error.

**Comment by coastforge-mei** [comment]
Due to bugs with Contao 4.9, I had to roll back my change to MCW for now. Unfortunately, I don't have the time to go deeper into this at the moment. I'll let you know as soon as I have any news. Maybe there is a possibility to change the project to Contao 4.9 in the meantime?

**Comment by fritzmg** [comment]
@Cleanerrr you need to run a full package update.
