### ISSUE TITLE
Filter von «reservation_object» bleibt leer

### ISSUE THREAD

**Issue by netzarbeiter** [Kuestenschmiede/ReservationBundle#15]
Contao 4.13.6
ReservationBundle 3.4.19

Das Feld «reservation_object» wird im Filter dargestellt, erhält jedoch leider keine Einträge.

Die Reservierungsart ist vom Objektyp «Contao Events».

![reservation_object](https://user-images.githubusercontent.com/1942550/184302026-328b00c5-5579-4d39-8ee8-91c40ee9c883.png)

**Comment by coastforge-mei** [comment]
Behoben mit der Version 3.4.20.
