### ISSUE TITLE
jQuery missing

### ISSUE THREAD

**Issue by PittRo** [Kuestenschmiede/ReservationBundle#16]
hello,
i get in frontend always the error "jQuery missing" inspite of having activated jQuery in sitelayout. On the other hand i tried to install https://packagist.org/packages/components/jquery as well but the error appears again.
I checked the loading order and can confirm that jQuery v3.6.0 loads before c4g-scripts are being processed.
PHP 7.4
Contao 4.9.16

**Comment by coastforge-mei** [comment]
Reservation uses con4gis/projects. jQuery 3.6 is loaded by this. If applicable, another error aborts this process. Are there any other issues in the log?

**Comment by coastforge-mei** [comment]
Our trainee has just integrated the reservation form into the page layout. This caused a similar error. If you have also done that, then include the module in an article instead. This way we might be able to figure out the problem. Thank you.

**Comment by coastforge-mei** [comment]
There may be problems with too many form fields once too many reservation types are selected in the form. This causes jQuery to break away. Presumably that will be the problem. We don't have a quick fix except to rely more on reservation objects or multiple frontend modules. We are working on a solution.

**Comment by PittRo** [comment]
No, my console is empty. I included the module right in a article, 
that doesn't seem to be the culprit.
We have only one reservation type configured.
Could you point to any possible implementation date, we going to implement the module at the end of august?

**Comment by coastforge-mei** [comment]
The bug should be fixed with 3.4.23. Please test it.

**Comment by PittRo** [comment]
Thanks it works fine.
