### ISSUE TITLE
div #c4g_condition mit eingenen Klassen versehen und ID entfernen

### ISSUE THREAD

**Issue by MacKP** [Kuestenschmiede/ReservationBundle#2]
Mir fällt gerade auf, dass beim Registrierungsformular alle divs um die Formularelemente keine eigene Klasse haben, dafür aber alle die id 'c4g_condition'. Wäre es möglich, den einzelnen divs eine eigene Klasse zugeben und eventuell auch eine eindeutige ID? Dann kann man die besser per CSS ansprechen ;-)

Viele Grüße

**Comment by coastforge-mei** [comment]
Ja, dass wird möglich sein. Die Felder werden zurzeit über unser Projects Framework generiert. Alles sehr "gewachsen" ;) Der Nachfolger ist bereits im Einsatz. Reservation wird aber erst im kommenden Jahr darauf umgestellt. Für die nächste Woche ist eine neue Reservation-Version eingeplant. Ich werde zu sehen, dass dann die Klassen schon mal mitkommen.

**Comment by coastforge-mei** [comment]
Mit der nächsten Version sind Klassen gesetzt.
