### ISSUE TITLE
Display error in the "Reservation option" field

### ISSUE THREAD

**Issue by drum-und-dran** [Kuestenschmiede/ReservationBundle#22]
Concerns version v3.4.29

The option "Objects multiple bookable" was not activated, nevertheless when clicking on multiple options they are displayed all under "Reservation option", not only once. 

See screenshot, **only the last clicked slot** should be listed here:
 

![193256806-7b0a3be3-9b3a-4986-b694-9127013fbfd5](https://user-images.githubusercontent.com/5277998/193776087-48e0db96-b9de-42c5-99db-535e1330d468.png)
 
 

Thanks and greetings,
Gunnar

**Comment by coastforge-mei** [comment]
The bug is fixed in version 3.4.30.
