### ISSUE TITLE
Bildauswahl fehlerhaft im Frontend (v3.4.31)

### ISSUE THREAD

**Issue by lennier83** [Kuestenschmiede/ReservationBundle#23]
![error_image_upload](https://user-images.githubusercontent.com/3589232/195565906-8d533f01-31d6-434f-b218-f529403a8cb2.JPG)

Bei einer Bildauswahl im Frontend via "CON4GIS-RESERVATION: OBJEKTPFLEGE" wird das Bild nicht ausgewählt:
mod_C4gReservationObjects -> c4g__form-file--image -> Uncaught ReferenceError: c4g_rq is not defined
- C4GBrickFileUpload bundles/con4gisprojects/dist/js/C4GBrickDialog.js?v=1664266502:1
- handleC4GBrickFile bundles/con4gisprojects/dist/js/C4GBrickDialog.js?v=1664266502:1
- onchange mitgliederbereich.html?object=test:1

**Comment by coastforge-mei** [comment]
Sorry, wir hatten den Fehler nicht mehr auf dem Schirm. Der Upload sollte mit der 3.4.32 wieder laufen.
