### ISSUE TITLE
Email an Inhaber des Eintrages Buggy

### ISSUE THREAD

**Issue by lennier83** [Kuestenschmiede/ReservationBundle#24]
Yesss! Das mit dem Bild funktioniert jetzt :-)
Es kommen leider keine Mails an ein Mitglied an. Also via ##member_email## via NotificationCenter wenn man was bucht was ein Mitglied eingestellt hat. Nur an hardcoded emails. Ging mal, deswegen vermutlich ein bug :-)

**Comment by coastforge-mei** [comment]
Wir prüfen das.

**Comment by lennier83** [comment]
Super. Nichts muss umsonst gemacht natürlich bei viel Aufwand. Ihr wisst wohin mit rechnungen :-D

**Comment by lennier83** [comment]
Juhuu.
Schon eine Info? Sonst schaue ich mal was gemacht wurde ab der Version wo das ging und haue (versuche) den Code in meine Installation mit den neuen versionsanpassungen :-)

**Comment by coastforge-mei** [comment]
Hey, wir haben auf jeden Fall eine entsprechende Korrektur gemacht. Ggf. noch nicht in der Version. Ich schaue mir mal die aktuellen Änderungen an ...

**Comment by coastforge-mei** [comment]
Teste mal die 3.4.33.

**Comment by lennier83** [comment]
Scheint zu klappen. Habe zuminest keine beschwerden vernommen :-)
