### ISSUE TITLE
Stornierung-Benachrichtigung funktioniert nicht

### ISSUE THREAD

**Issue by Cleanerrr** [Kuestenschmiede/ReservationBundle#28]
Hi
ich habe ein Modul zum Stornieren einer Reservierung erstellt. Außerdem habe ich eine neue Unterseite für das Stornierungsformular erstellt, auf der ich das Modul platziert habe. Im Modul habe ich die Stornierung-Benachrichtigung aktiviert, die ich zuvor auch erstellt habe. In der Benachrichtigung zur Reservierung habe ich einen Link gesetzt, der auf die Unterseite führt, auf der sich das Modul zur Stornierung der Reservierung befindet. Ein Klick auf den Link öffnet die Unterseite „Stornierung“ und auch dieses Stornierungsformular funktioniert. Am Ende des Absendens der Stornierung werden die Bedingungen storniert, also funktioniert alles. Grundsätzlich habe ich alles wie in der Dokumentation beschrieben eingerichtet. 
Bei einer Reservierung kommen Benachrichtigungen problemlos an, bei einer Stornierung jedoch nicht. Wenn ich zum Beispiel die Stornierung-Benachrichtigung im Reservierungsformular aktiviere, dann funktioniert es und die Benachrichtigung kommt an, aber wenn es dort aktiviert ist, wo es sein sollte, im Stornierungsmodul, dann funktioniert es nicht. 
Liegt das Problem hier am Notification-Center-Modul oder habe ich etwas nicht richtig eingestellt?

Edit: Ich habe mit der Eingabe einer E-Mail-Adresse anstelle eines Tokens (##email## und ##admin_email##) getestet und festgestellt, dass es so funktioniert. Das Problem liegt also in Tokens. Es kann vorübergehend mit einer E-Mail-Adresse verwendet werden, jedoch nur, wenn eine Benachrichtigung an den Administrator gesendet wird. Die Benachrichtigung zum Senden an den Benutzer funktioniert immer noch nicht.

Danke im Voraus
Gruß

**Comment by coastforge-mei** [comment]
Bisher hat die Stornierungsbenachrichtigung immer funktioniert. Evtl. ist mit der 3.6 etwas kaputt gegangen. Wir prüfen das.

**Comment by coastforge-mei** [comment]
Wir haben die Stornierung in mehreren Umgebungen getestet. Die Benachrichtigung wird korrekt versendet. D.h., die Wahrscheinlichkeit ist groß, dass es an Deiner Konfiguration liegt. Evtl. nutzt Du das falsche Empfänger-Token. Richtig ist: email

**Comment by Cleanerrr** [comment]
Ich glaube, ich habe irgendwo etwas falsch gemacht. Hier sind Screenshots dieser Module und Benachrichtigung:
![st1](https://user-images.githubusercontent.com/30474317/227921347-87550e41-e1a8-4e74-8e23-818ccba176cf.jpg)
![st2](https://user-images.githubusercontent.com/30474317/227921355-ca039de1-5976-4adb-9f9a-e28db321f803.jpg)
Muss man die Benachrichtigung woanders aktivieren?

**Comment by coastforge-mei** [comment]
Der Absender darf bei Deinem E-Mail-Server vermutlich nicht email sein. D.h. Du trägst die Server-Adresse ein und trägst email als reply to Adresse ein. Falls Du das überhaupt so brauchst? email ist ja der Stornierende.

**Comment by Cleanerrr** [comment]
Es funktioniert immer noch nicht. 
Wenn Sie möchten, kann ich Ihnen (per E-Mail) einen Zugang zur Testumgebung zukommen lassen, damit Sie einen Blick darauf werfen können?

**Comment by Cleanerrr** [comment]
jetzt funktioniert es aber. Ich habe in beiden Fällen die E-Mail des Absenders gelöscht und nur die E-Mail des Empfängers festgelegt, für den Administrator meine E-Mail und für den Benutzer das Token "E-Mail". Es funktioniert jetzt. 
Vielen Dank für Ihre Unterstützung und die sehr schnellen Antworten.

**Comment by Cleanerrr** [comment]
Hi, 
ich poste hier nochmal, um kein neues Thema zu eröffnen, weil ich mir nicht sicher bin, ob es ein Fehler ist oder ob ich etwas falsch eingestellt habe. 
Der Kunde sucht nämlich auf seiner Website nach Reservierungen, um einen wöchentlichen Termin zu reservieren, der ausschließlich montags beginnt und bis Samstag dauert. Eine anderweitige Reservierung ist nicht möglich. Es gibt nur drei Mal pro Tag, erstes Termin von 09:00 bis 10:30 Uhr, das zweite von 14:00 bis 15:30 Uhr und das dritte von 16:00 bis 17:30 Uhr. Ich habe drei Objekte erstellt, die in meinem Fall die drei angegebenen Termine sind. Alle drei Einrichtungen haben die Start- und Endzeit der Reservierung nur montags eingetragen. Damit habe ich es unmöglich gemacht, Termine an anderen Tagen als montags zu buchen. Ich hoffe das ist kein Problem? Ich habe eine Reservierungsart vorgenommen und festgelegt, dass die Reservierung wöchentlich erfolgt. Allerdings stoße ich auf ein paar Probleme. Im Feld „Reservierungsmöglichkeit“ stehen also, wie im Screenshot zu sehen, zwei Starttermine. Ich habe alle möglichen Varianten ausprobiert, die mir eingefallen sind, aber ich konnte das nicht beheben. Ist das ein Fehler oder eine falsche Einstellung? Ist es möglich, dieses Feld vollständig zu entfernen? Ich habe versucht, es in Vorlagen zu finden, aber ich habe keine Vorlage für dieses Formular in Contao gefunden. 
Eine andere Sache sind die Start- und Endzeiten des reservierten Termins, wo Sie sehen können, dass die Reservierung in allen Fällen eine Stunde später als geplant beginnt und um 02:00 Uhr endet, was unlogisch ist. Beispielsweise ist die Reservierung vom 04.03.2023-04.09.2023 von 09:00-10:30, und im Frontend wird angezeigt, dass die Reservierung vom 04.03.2023-04.09.2023 von 10:00-02:00 ist . Was könnte hier das Problem sein? 
Und das dritte sind die Namen "Reservierungsbeginn", "Reservierungszeitraum" und "Reservierungsmöglichkeit". Wo ändere ich diese Namen? Ansonsten ändere ich die Namen in "contao/dca/naziv_tabele.php", in der ich "$GLOBALS['TL_DCA']['tl_example']... usw" eintrage, aber ich habe es nicht geschafft zu verstehen, in welcher Tabelle ich die Namen ändere . Es wäre wirklich nett, wenn Sie mir sagen könnten, wo ich das ändern kann.
Danke im Voraus für die Antworten.
LG
![cgb-er-1](https://user-images.githubusercontent.com/30474317/228753558-5354d9ad-bb63-4926-ac94-0a862d115565.jpg)

**Comment by coastforge-mei** [comment]
Die Label findest Du, wie im Contao-Standard in den Language-Dateien, die Du überschreiben kannst (siehe Contao Doku). Beispielsweise diesen Eintrag: 
$GLOBALS['TL_LANG']['fe_c4g_reservation']['reservation_object'] = 'Reservierungsmöglichkeit';

Wenn ich Dich richtig verstehe, dann arbeitest Du mit drei Objekten die unterschiedliche Zeiten benötigen. Normalerweise sollte es so sein, dass bei der Intervallart "Tage" (nicht Übernachtungen). Immer die Endzeit des letzten Tages genutzt wird. 
D.h. Objekt1: montags **9:00**-10:30 Uhr, samstags: 9:00-**10:30** Uhr (Intervall 6 Tage)
u.s.w.

Die fett markierten sollten dann am Objekt dargestellt werden. Wir testen das auch noch mal.

Beim nächsten Mal bitte bei einem neuen Thema auch ein neues Issue aufmachen. Danke.

**Comment by coastforge-mei** [comment]
Wenn Du am Samstag die Beginnzeit raus lässt. Dann steht der Samstag auch nicht zur Buchung zur Verfügung und die Endzeit wird trotzdem für die Darstellung genommen.

**Comment by Cleanerrr** [comment]
Vielen Dank für die Antworten. 
Ich habe die gesamte Konfiguration geändert und jetzt ist mir klarer, wie ich ans Ziel komme. Ich habe noch immer ein Problem mit der Startzeit der Reservierung. Beispielsweise beginnt der Termin um 09:00 Uhr und im Frontend steht 10:00 Uhr. Warum ist die Stunde später? 
Und noch eine Frage, warum habe ich im letzten Feld des Screenshots zwei Daten?
Danke

**Comment by coastforge-mei** [comment]
Jo, beide Fehler haben wir auch schon entdeckt. Wir sind gerade dran das zu beheben. Ich befürchte, dass uns die Sommerzeit da rein gerutscht ist ... Wir schließen das ToDo ab sobald die 3.6.1 erstellt ist.

**Comment by Cleanerrr** [comment]
OK, alles klar. Vielen Dank
