### ISSUE TITLE
Problem in der Version 3.6.2

### ISSUE THREAD

**Issue by netzarbeiter** [Kuestenschmiede/ReservationBundle#29]
Habe soeben das System aktualisiert, damit die Bestellungen wieder funktionieren musste ich im ReservationBundle zurück auf Version 3.6.1.

Die Fehlermeldung auf der Bestellseite:

`[2023-04-05T14:50:50.532171+02:00] request.CRITICAL: Uncaught PHP Exception TypeError: "shuffle(): Argument #1 ($array) must be of type array, con4gis\ReservationBundle\Classes\Objects\C4gReservationFrontendObject given" at /home/user/public_html/example.com/vendor/con4gis/reservation/src/Classes/Utils/C4gReservationHandler.php line 933 {"exception":"[object] (TypeError(code: 0): shuffle(): Argument #1 ($array) must be of type array, con4gis\\ReservationBundle\\Classes\\Objects\\C4gReservationFrontendObject given at /home/user/public_html/example.com/vendor/con4gis/reservation/src/Classes/Utils/C4gReservationHandler.php:933)"} []`

**Comment by coastforge-mei** [comment]
Danke für die Meldung. Wir schauen uns das an. Der Fehler tritt ggf. nur auf, wenn lediglich ein Object (Event) vorhanden ist. In unseren Tests trat der Fehler bisher nicht auf. So oder so können wir den Fehler abfangen.

**Comment by netzarbeiter** [comment]
Sag mir wenn du noch was brauchst oder wenn ich testen soll.

**Comment by coastforge-mei** [comment]
Das Problem sollte mit Version 3.6.3 behoben sein. Bitte testen.

**Comment by netzarbeiter** [comment]
Das Problem ist mit Version 3.6.3 behoben. Herzlichen Dank.
