### ISSUE TITLE
Es ist mögliche vergangene Termine zu buchen

### ISSUE THREAD

**Issue by MacKP** [Kuestenschmiede/ReservationBundle#3]
Hallo :)
Mir ist aufgefallen, dass ich vergangene Termine an einem Tag buchen kann. Also das heutige Datum auswählen und dann kann ich auch um 11 Uhr noch die Termine ab 8 / 9 / 10 Uhr auswählen.
Es wäre schön, wenn die nicht mehr verfügbar sind oder zumindest als solche markiert werden.

Viele Grüße

**Comment by coastforge-mei** [comment]
So ein Problem sollte nicht auftreten. Kannst Du mir Deine Konfiguration per E-Mail zukommen lassen? Ggf. als SQL-Export der Reservation Tabellen?  Wichtig sind Reservierungsart und die Objekte. Danke.

**Comment by MacKP** [comment]
Hm gerade kann ich das Problem auch nicht mehr nachstellen. Keine Ahnung warum. Die Konfiguration hab ich erst mal nicht weiter angefasst gehabt. Naja, solange es geht bin ich zufrieden ;-)

Viele Dank!
