### ISSUE TITLE
Problem in der Version 3.6.6

### ISSUE THREAD

**Issue by netzarbeiter** [Kuestenschmiede/ReservationBundle#30]
Bei der System-Aktualisierung wurde das ReservationBundle auf die Version 3.6.6 angehoben.

Auf der Bestätigungsseite erhalte ich folgende Fehlermeldung und die Bestellung wird nicht abgeschlossen.

```
Bestellen
Error3: [object Object]
```

Aus dem Log:
`[2023-04-26T09:11:33.718314+02:00] request.CRITICAL: Uncaught PHP Exception TypeError: "Unsupported operand types: string * int" at /home/user/public_html/example.com/vendor/con4gis/reservation/src/Controller/C4gReservationController.php line 1671 {"exception":"[object] (TypeError(code: 0): Unsupported operand types: string * int at /home/user/public_html/example.com/vendor/con4gis/reservation/src/Controller/C4gReservationController.php:1671)"} []`

Bin jetzt auf die Version [3.6.3](https://github.com/Kuestenschmiede/ReservationBundle/issues/29) zurück.

**Comment by coastforge-mei** [comment]
Der Fehler ist mit der Version 3.6.8 behoben.

**Comment by netzarbeiter** [comment]
Vielen Dank, Matthias
