### ISSUE TITLE
Reservationobject time false

### ISSUE THREAD

**Issue by mammut47** [Kuestenschmiede/ReservationBundle#31]
i created a reservation object with fixed date and time
![image](https://github.com/Kuestenschmiede/ReservationBundle/assets/12047148/7ac1b0bd-c37e-4fbf-b439-83e51b682c21)
But in Frontend it shows the time with one hour minus.
Instead 11:00 it shows 10:00
I do not find any configuration for summer/winter time.
Contao 4.13
PHP 8.2

**Comment by mammut47** [comment]
Timezone in Contao: Europe/Berlin
Timezone OS: Europe/Berlin

**Comment by Tomatenmarc22** [comment]
Hello mammut47, 

we are looking into the issue and will get back to you as soon as we have recreated
and resolved the problem.

Best regards
Marc

**Comment by Tomatenmarc22** [comment]
There will be another version coming out soon that will fix this issue.

Thank you for your patience
