### ISSUE TITLE
Es werden nicht alle simple Tokens ersetzt

### ISSUE THREAD

**Issue by MacKP** [Kuestenschmiede/ReservationBundle#4]
Ich hab jetzt noch nicht alle getestet, aber es werden nicht alle Simple Tonkens ersetzt. Die funktionieren nicht:
```
##reservation_date##
##reservation_time##
##endDate##
```
Es wäre auch schön, wenn es einen Simple Token geben würde, der einem einfach alles aus gibt. Normalerweise ist das:##raw_data##

Viele Grüße

**Comment by coastforge-mei** [comment]
##endDate## ist ggf. nicht gesetzt. Das wird für mehrtägige Reservierungen dann irgendwann interessant. Ich kann das aber prüfen und werde dann den selben Tag mitgeben. reservation_date und _time schaue ich mir an. Das scheint eine Altlast zu sein. Ich werde die beiden Tokens raus schmeißen. Die Werte müssten in ##beginDate## und ##beginTime## stehen.

##raw_data## bringe ich als ToDo in die Planung. 

Besten Dank für Dein Feedback.

**Comment by MacKP** [comment]
Super, Danke!

**Comment by MacKP** [comment]
Passend zum Thema eventuell auch noch die Anmerkung: Leider wird der ##business_email## nur in dem Textbereich der E-Mail unterstützt und nicht in den Meta-Informationen der Nachricht. D.h. ich kann leider nicht individuell an die einzelnen Leute (dich ich konfiguriert habe) eine E-Mail versenden.
Um das zu erreichen müsste ich gerade 5 Formulare bauen ><
Wäre schön, wenn das noch geändert werden könnte.

Viele Grüße

**Comment by MacKP** [comment]
Einen hab ich noch... in der config.php fehlt auch noch der Token ##organisation## ;-)

**Comment by coastforge-mei** [comment]
Mit der nächsten Version sind die fehlenden Tokens alle drin. Die business_ werden in contact_ umbenannt sein. Und nur als Hinweis: aufgrund zahlreicher Erweiterungen zum Thema Seminarreservierung wird es ein Major-Release werden. Die Konfiguration des Veranstaltungsorts ist aber eine der wenigen Ausnahmen die nach einem Update angepasst werden müssen.
