### ISSUE TITLE
Uhrzeit nicht Buchbar, wenn es der selbe Tag wie heute ist und es später ist.

### ISSUE THREAD

**Issue by MacKP** [Kuestenschmiede/ReservationBundle#6]
Guten Morgen,
mir ist aufgefallen, dass ich zukünftige Reservierungen nicht buchen kann, wenn es der selbe Tag wie heute ist, die Uhrzeit aber schon abgelaufen ist.
Beispiel:
Heute (Dienstag, der 08.12.2020 08:14 Uhr) der Termin um 7:00 bis 8:00 Uhr ist nicht mehr buchbar. Gleichzeitig ist der Termin in der nächsten Woche (Dienstag, der 15.12.2020) um 7:00 b9s 8:00 Uhr auch nicht mehr buchbar. Den kann ich erst morgen wieder buchen, da dann die Überprüfung auf Mittwoch stattfindet.

Viele Grüße

**Comment by coastforge-mei** [comment]
Guten Morgen,
dass ist ärgerlich. Sorry. Wir werden das schnellstmöglich korrigieren.
Beste Grüße
Matthias

**Comment by coastforge-mei** [comment]
Moin, 
auch dieser Fehler ist in der 2.0.0 behoben. Herzlichen Dank für Dein Feedback.
Sonnige Grüße
Matthias
