### ISSUE TITLE
Reservierung buchbar, obwohl die Anfangszeit überschritten ist

### ISSUE THREAD

**Issue by MacKP** [Kuestenschmiede/ReservationBundle#7]
Guten Morgen,
mir ist aufgefallen, dass ein Termin noch buchbar ist, wenn die Anfangszeit schon überschritten wurde. Ich habe Termine angelegt, die eine Stunde lang sind. Um 8:15 (also bis 9 Uhr) kann ich den Termin von 08:00 bis 09:00 Uhr noch buchen. Es wäre glaube ich praktischer, wenn die Überprüfung im Frontend nicht auf die Endzeit, sondern auf die Anfangszeit reagieren würde.
Oder das sollte wenigstens konfigurierbar sein, damit man das selber entscheiden kann ;-)

Viele Grüße

**Comment by coastforge-mei** [comment]
Moin,
ja, dass stimmt. Wir werden das prüfen und abstellen.
Danke

**Comment by coastforge-mei** [comment]
Hi, der Fehler sollte in der 2.0.0 behoben sein.
